title: Dairy of Aman Jain
author: Aman Jain 
email: amanj13508@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  In this blog, I am going to write my thoughts about different things
  that I encounter or cross my mind on a daily basis.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
